name: Hwang blog
description: Blogging about stuffs
meta_description: "공부 또는 경험에 대한 기록"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /hwang
domain_name: "http://hwangblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Hwang Jeong Hyeon"

# Disqus config
disqus-shortname: ""
